services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: amazon-order-trends
    ports:
      - "3000:3000" # React frontend
      - "5001:5001" # Flask backend
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      # --- Add FLASK_APP to tell Flask where the app is ---
      - FLASK_APP=backend.api:create_app
      - PYTHONPATH=/app
      - FLASK_ENV=development
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - WATCHPACK_POLLING=true
      - MIGRATIONS_DIR=/app/backend/migrations/versions
    # command: >
    #   sh -c "
    #     echo 'Waiting for database...' && sleep 5 &&
    #     echo 'Initializing database...' && flask init-db &&
    #     echo 'Starting development servers...' &&
    #     flask run --host=0.0.0.0 --port=5001 &
    #     npm start --prefix frontend
    #   "
    command: sh /app/start-dev.sh
    restart: unless-stopped

